version: '3'

services:
  platosbygloria:
    container_name: platosbygloria
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    build: .
    volumes:
      - .:/app

    ports:
      - 3000:3000
    
    command: npm start
networks:
  proxy:
    external: true