export const FETCH_ALL_PLATES_PENDING = 'FETCH_ALL_PLATES_PENDING';
export const FETCH_ALL_PLATES_SUCCESS = 'FETCH_ALL_PLATES_SUCCESS';
export const FETCH_ALL_PLATES_FAILED = 'FETCH_ALL_PLATES_FAILED';

export const FETCH_ONE_PLATE_PENDING = 'FETCH_ONE_PLATE_PENDING';
export const FETCH_ONE_PLATE_SUCCESS = 'FETCH_ONE_PLATE_SUCCESS';
export const FETCH_ONE_PLATE_FAILED = 'FETCH_ONE_PLATE_FAILED';

export const ADD_ONE_PLATE_PENDING = 'ADD_ONE_PLATE_PENDING';
export const ADD_ONE_PLATE_SUCCESS = 'ADD_ONE_PLATE_SUCCESS';
export const ADD_ONE_PLATE_FAILED = 'ADD_ONE_PLATE_FAILED';

export const UPDATE_ONE_PLATE_PENDING = 'UPDATE_ONE_PLATE_PENDING';
export const UPDATE_ONE_PLATE_SUCCESS = 'UPDATE_ONE_PLATE_SUCCESS';
export const UPDATE_ONE_PLATE_FAILED = 'UPDATE_ONE_PLATE_FAILED';

export const DELETE_ONE_PLATE_PENDING = 'DELETE_ONE_PLATE_PENDING';
export const DELETE_ONE_PLATE_SUCCESS = 'DELETE_ONE_PLATE_SUCCESS';
export const DELETE_ONE_PLATE_FAILED = 'DELETE_ONE_PLATE_FAILED';

export const DELETE_PLATES_PENDING = 'DELETE_PLATES_PENDING';
export const DELETE_PLATES_SUCCESS = 'DELETE_PLATES_SUCCESS';
export const DELETE_PLATES_FAILED = 'DELETE_PLATES_FAILED';