export const FETCH_ALL_CUSTOMERS_PENDING = 'FETCH_ALL_CUSTOMERS_PENDING';
export const FETCH_ALL_CUSTOMERS_SUCCESS = 'FETCH_ALL_CUSTOMERS_SUCCESS';
export const FETCH_ALL_CUSTOMERS_FAILED = 'FETCH_ALL_CUSTOMERS_FAILED';

export const FETCH_ONE_CUSTOMER_PENDING = 'FETCH_ONE_CUSTOMER_PENDING';
export const FETCH_ONE_CUSTOMER_SUCCESS = 'FETCH_ONE_CUSTOMER_SUCCESS';
export const FETCH_ONE_CUSTOMER_FAILED = 'FETCH_ONE_CUSTOMER_FAILED';

export const ADD_ONE_CUSTOMER_PENDING = 'ADD_ONE_CUSTOMER_PENDING';
export const ADD_ONE_CUSTOMER_SUCCESS = 'ADD_ONE_CUSTOMER_SUCCESS';
export const ADD_ONE_CUSTOMER_FAILED = 'ADD_ONE_CUSTOMER_FAILED';

export const UPDATE_ONE_CUSTOMER_PENDING = 'UPDATE_ONE_CUSTOMER_PENDING';
export const UPDATE_ONE_CUSTOMER_SUCCESS = 'UPDATE_ONE_CUSTOMER_SUCCESS';
export const UPDATE_ONE_CUSTOMER_FAILED = 'UPDATE_ONECUSTOMERE_FAILED';

export const DELETE_ONE_CUSTOMER_PENDING = 'DELETE_ONE_CUSTOMER_PENDING';
export const DELETE_ONE_CUSTOMER_SUCCESS = 'DELETE_ONE_CUSTOMER_SUCCESS';
export const DELETE_ONE_CUSTOMER_FAILED = 'DELETE_ONE_CUSTOMER_FAILED';